name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'malagu*'
      - '!**.md'
  workflow_dispatch:

env:
  NODE_VERSION: '16'
  FC_REGION: 'cn-zhangjiakou'

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0

      - uses: firenza/verify-secrets@v2
        with:
          secrets: ${{ toJSON(secrets) }}
          exclusions: GITHUB_TOKEN

  deploy-branch:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || github.ref_name == 'develop'
    needs: [check-secret]
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: bahmutov/npm-install@v1.10.3
      - run: |
          echo "MALAGU_REGION=${{ env.FC_REGION }}" >> $GITHUB_ENV
          echo "MALAGU_ACCOUNT_ID=${{ secrets.FC_ID }}" >> $GITHUB_ENV
          echo "MALAGU_ACCESS_KEY_ID=${{ secrets.FC_AK }}" >> $GITHUB_ENV
          echo "MALAGU_ACCESS_KEY_SECRET=${{ secrets.FC_SK }}" >> $GITHUB_ENV
      - if: github.ref_name == 'develop'
        run: npm run deploy:development
      - if: github.ref_name == 'main'
        run: npm run deploy:production
